#!/bin/sh
# Install the git hooks that keep private data out of this public repo.
set -eu

root=$(git rev-parse --show-toplevel)
hooks=$(git rev-parse --git-path hooks)
mkdir -p "$hooks"

cat > "$hooks/pre-commit" <<'HOOK'
#!/bin/sh
# Generated by scripts/install-hooks.sh
exec python3 "$(git rev-parse --show-toplevel)/scripts/check-no-private-data.py"
HOOK

cat > "$hooks/commit-msg" <<'HOOK'
#!/bin/sh
# Generated by scripts/install-hooks.sh
exec python3 "$(git rev-parse --show-toplevel)/scripts/check-no-private-data.py" \
    --commit-msg "$1"
HOOK

chmod +x "$hooks/pre-commit" "$hooks/commit-msg"
echo "Installed pre-commit and commit-msg hooks in $hooks"

if [ ! -f "$root/.private-terms" ]; then
    cat > "$root/.private-terms" <<'TERMS'
# Local, git-ignored. One term per line: the real names, hostnames and
# addresses of YOUR instance, so the checker rejects them if they ever end up
# in a tracked file. Never commit this file -- .gitignore already excludes it.
TERMS
    echo "Created a starter .private-terms (git-ignored) -- add your own terms."
fi
